export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$PATH:~/.cabal/bin"
export PATH="$PATH:~/.cargo/bin"
export PATH="~/.local/bin:$PATH"
export PATH="$PATH:~/go/bin"
export PATH="$PATH:/snap/bin"
export PATH="$PATH:$HOME/.pyenv/bin"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"

source ~/.antigenrc
source /usr/share/doc/fzf/examples/key-bindings.zsh

alias vim="emacs -nw"
alias ls=exa
alias ta="tmux attach"
alias cat=bat
# alias docker=podman

##
# Load any extra Zshell profile scripts
##
if [[ -d ~/.profile.d  ]]; then
   for f in ~/.profile.d/*.zsh; do
       source "$f"
    done
fi

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

source <(kubectl completion zsh)
[[ /snap/bin/kubectl ]] && source <(kubectl completion zsh)
fpath=($fpath ~/.zsh/completion)
