
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"

source $HOME/.antigenrc
source /usr/share/doc/fzf/examples/key-bindings.zsh


# alias docker=podman

##
# Load any extra Zshell profile scripts
##
if [[ -d $HOME/.profile.d  ]]; then
   for f in $HOME/.profile.d/*.zsh; do
       source "$f"
    done
fi

[[ /snap/bin/kubectl ]] && source <(kubectl completion zsh)

fpath=($fpath $HOME/.zsh/completion)

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
[ -f $HOME/.antigenrc ] && source $HOME/.antigenrc

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:/snap/bin"
export PATH="$PATH:$HOME/.pyenv/bin"
export PATH="$PATH:$HOME/.emacs.d/bin"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

alias ls=exa
alias vim="emacs -nw"
alias ta="tmux attach"
alias cat=bat

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

source <(kubectl completion zsh)
[[ /snap/bin/kubectl ]] && source <(kubectl completion zsh)
fpath=($fpath $HOME/.zsh/completion)

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
