- name: Local Bookkeeping tasks
  hosts: local
  tasks: []

- name: Debug values
  hosts: local
  tasks:
    - debug:
        var:
          - ansible_os_family
        verbosity: 1
      tags:
        - "git"
        - "fzf"
        - "zsh"
        - "tmux"
        - "emacs"
        - "doom-emacs"
        - "vim"
        - "rust"
        - "sway"
        - "wm"
        - "packages"

- name: Set up local development environment
  hosts: local
  roles:
    - role: git
      tags:
        - "git"
    # - {role: fish, tags: ['fish']}
    - role: fzf
      tags:
        - "fzf"
    - role: zsh
      tags:
        - "zsh"
    - role: tmux
      tags:
        - "tmux"
    - role: emacs
      tags:
        - "emacs"
        - "doom-emacs"
    - role: vim
      tags:
        - "vim"
    - role: nvim
      tags:
        - "nvim"
    # - role: haskell
    #   tags:
    #     - "stack"
    - role: programming
      tags:
        - "rustup"
        - "cargo"
        - "rust"
        - "go"
        - "programming"
    - role: sway
      tags:
        - "sway"
        - "wm"
    # - role: penrose
    #   tags:
    #     - "wm"
    #     - "penrose"
    #     - "bspwm"
    # - role: xmonad
    #   tags:
    #     - "xmonad"
    - role: firefox
      tags:
        - firefox
    - role: packages
      tags:
        - "packages"
