- name: Install pacman packages
  community.general.pacman:
    name:
      - qemu
      - virt-manager
      - pcmanfm
      - npm
      - autorandr
      - arandr
      - bash-language-server
  become: true
  become_method: sudo
