- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install bash-language-server
  community.general.npm:
    name: "bash-language-server"
    global: true
  become: true
  become_method: sudo

- name: install prettier
  community.general.npm:
    name: "prettier"
    global: true
  become: true
  become_method: sudo
