- name: Create wired config directory
  file:
    path: "{{ xdg_config_home }}/wired"
    state: directory

- name: Hard link wired configuration
  file:
    src: "{{ dotfiles_home }}/roles/wired/files/wired.ron"
    dest: "{{ xdg_config_home }}/wired/wired.ron"
    state: hard
    force: true
