#! /bin/bash

_bc() {
    bspc config "$@"
}

_check() {
    command -v "$1" > /dev/null
}



bspc monitor -d 1 2 3 4 5 6 7 8 9

# Window Management
_bc border_width 1
_bc window_gap 0

_bc split_ratio          0.67
_bc borderless_monocle   true
_bc gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart

pgrep -x sxhkd > /dev/null || sxhkd &

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
# Launch Polybar
if _check polybar
then
    bash $HOME/.config/polybar/launch.sh &

    # Add padding equal to the panel height to fix an issue where there
    # is an overlap between panel and windows.
    _panel_height() {
        awk -F '=' '/height/ { print $2; exit; }' \
            "$HOME"/.config/polybar/config
    }
fi

if [ -x /usr/local/bin/polybar ]; then
fi
# _check xsetroot &&
xsetroot -xcf /usr/share/icons/DMZ-White/cursors/left_ptr 16 -solid black
_check rescuetime && rescuetime &
