#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e
EXE_NAME=my-xmonad
OUTPUT=$1

stack build
stack install ":$EXE_NAME" --local-bin-path bin/
mv "bin/$EXE_NAME" "$OUTPUT"
