- name: Install compilation dependencies
  apt:
    name:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - python3
      - libssl-dev
      - lld
    state: present
    force_apt_get: yes
  become: true
  become_method: sudo

- name: Install go
  snap:
    name:
      - go
    state: present
    classic: true
  become: true
  become_method: sudo
