- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install rustup
  command: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/rustup"

- name: Install rust-analyzer server
  get_url:
    url: "https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux"
    dest: "{{ dotfiles_user_home }}/.local/bin/rust-analyzer"
    mode: 0755

- name: Install fun crates
  command: "cargo install {{ item.name }}"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/{{ item.exe }}"
  with_items:
  - name: exa
    exe: exa
  - name: bat
    exe: bat
  - name: ripgrep
    exe: rg
  - name: cargo-edit
    exe: cargo-add

- name: Alacritty config dir
  file:
    path: "{{ dotfiles_user_home }}/.config/alacritty"
    state: directory

- name: Alacritty config
  file:
    src: "{{ dotfiles_home }}/roles/programming/files/alacritty.yml"
    dest: "{{ dotfiles_user_home }}/.config/alacritty/alacritty.yml"
    state: link
    force: true
