- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Arch"

- name: download rustup
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rustup.sh"

- name: install rustup
  command: "sh /tmp/rustup.sh -y"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/rustup"

- name: Install fun crates
  command: "{{ dotfiles_user_home }}/.cargo/bin/cargo install {{ item.name }}"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/{{ item.exe }}"
  with_items:
  - name: cargo-binstall
    exe: cargo-binstall
  - name: cargo-edit
    exe: cargo-add
  - name: sccache
    exe: sccache

- name: Install fun crates
  command: "{{ dotfiles_user_home }}/.cargo/bin/cargo binstall {{ item.name }}"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/{{ item.exe }}"
  with_items:
  - name: eza
    exe: eza
  - name: bat
    exe: bat
  - name: ripgrep
    exe: rg
  - name: zoxide
    exe: z
  - name: zellij
    exe: zellij

- name: Alacritty config dir
  file:
    path: "{{ dotfiles_user_home }}/.config/alacritty"
    state: directory

- name: Alacritty config
  file:
    src: "{{ dotfiles_home }}/roles/programming/files/alacritty.toml"
    dest: "{{ dotfiles_user_home }}/.config/alacritty/alacritty.toml"
    state: link
    force: true

- name: Remove rls
  file:
    dest: "{{ dotfiles_user_home }}/.cargo/bin/rls"
    state: absent

# - name: Checkout rust-analyzer
#   git:
#     repo: https://github.com/rust-analyzer/rust-analyzer.git
#     dest: "{{ dotfiles_user_home }}/git/utilities/rust-analyzer"
#     update: no

# - name: Install rust-analyzer
#   command: "cargo xtask install --server"
#   args:
#     chdir: "{{ dotfiles_user_home }}/git/utilities/rust-analyzer"
