- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
- include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: download rustup
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rustup.sh"

- name: install rustup
  command: "sh /tmp/rustup.sh -y"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/rustup"

- name: Install rust-analyzer component
  command: "{{ dotfiles_user_home }}/.cargo/bin/rustup component add rust-analyzer"
  changed_when: false

- name: Install cargo-binstall and lspmux
  command: "{{ dotfiles_user_home }}/.cargo/bin/cargo install {{ item.name }}"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/{{ item.exe }}"
  with_items:
    - name: cargo-binstall
      exe: cargo-binstall
    - name: lspmux
      exe: lspmux

- name: Install useful crates
  command: "{{ dotfiles_user_home }}/.cargo/bin/cargo-binstall -y {{ item.name }}"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/{{ item.exe }}"
  with_items:
    - name: cargo-edit
      exe: cargo-add
    - name: sccache
      exe: sccache
    - name: eza
      exe: eza
    - name: bat
      exe: bat
    - name: ripgrep
      exe: rg
    - name: zoxide
      exe: zoxide
  when: not ansible_check_mode

- name: Kitty config dir
  file:
    path: "{{ xdg_config_home }}/kitty"
    state: directory

- name: Kitty config
  file:
    src: "{{ dotfiles_home }}/roles/programming/files/kitty.conf"
    dest: "{{ xdg_config_home }}/kitty/kitty.conf"
    state: link
    force: true

- name: Remove rls
  file:
    dest: "{{ dotfiles_user_home }}/.cargo/bin/rls"
    state: absent

# - name: Checkout rust-analyzer
#   git:
#     repo: https://github.com/rust-analyzer/rust-analyzer.git
#     dest: "{{ dotfiles_user_home }}/git/utilities/rust-analyzer"
#     update: no

# - name: Install rust-analyzer
#   command: "cargo xtask install --server"
#   args:
#     chdir: "{{ dotfiles_user_home }}/git/utilities/rust-analyzer"

- name: Ensure systemd user directory exists
  file:
    path: "{{ dotfiles_user_home }}/.config/systemd/user"
    state: directory

- name: Install lspmux systemd user service unit
  template:
    src: lspmux.service.j2
    dest: "{{ dotfiles_user_home }}/.config/systemd/user/lspmux.service"

- name: Enable and start lspmux service
  systemd:
    name: lspmux
    scope: user
    enabled: yes
    masked: no
    state: started
    daemon_reload: yes
