- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    state: link
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{ dotfiles_user_home }}/.tmux.conf"

- name: tmux folder
  file:
    state: directory
    dest: "{{ dotfiles_user_home }}/.tmux/keybindings"

- name: Symlink keybindings
  file:
    state: link
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux/keybindings/{{ item }}"
    dest: "{{ dotfiles_user_home }}/.tmux/keybindings/{{ item }}"
  loop:
    - f-keys.conf
    - f-keys.conf.disable
