- name: Install bspwm dependencies
  apt:
    name:
    - libglib2.0-dev
    - libpango1.0-dev
    - libcairo2-dev
    - libasound2-dev
    - libgirepository1.0-dev
    - libxcb-randr0-dev
    - libwebkit2gtk-4.0-dev
    - libgtksourceview-3.0-dev
    - libtinfo-dev
    - libdbusmenu-glib-dev
    - libdbusmenu-gtk3-dev
    - thunar
    - suckless-tools
    - xsecurelock
    - polybar
    - blueman
    - nitrogen
    - sxhkd
    - picom
    - bspwm
    - rofi
    - dunst
    - jq
    - tint2
    state: present
    force_apt_get: yes
  become: true
  become_method: sudo
