- name: Install sway packages
  community.general.pacman:
    name:
      - sway
      - waybar
      - rofi
      - i3status
      - swayidle
      - swaylock
      - alacritty
      - light
      - ranger
      - powerline-fonts
      - nnn
      - grim
      - playerctl
  become: true
  become_method: sudo
