packages:
- .
extra-deps:
- ConfigFile-1.1.4
- X11-1.9
- broadcast-chan-0.2.0.2
- cairo-0.13.6.1
- dbus-hslogger-0.1.0.1
- gi-cairo-connector-0.0.1
- gi-cairo-render-0.0.1
- gi-dbusmenu-0.4.6
- gi-dbusmenugtk3-0.4.7
- gi-gdkx11-3.0.8
- gi-xlib-2.0.7
- gio-0.13.6.1
- glib-0.13.7.1
- gtk-sni-tray-0.1.6.0
- gtk-strut-0.1.3.0
- gtk2hs-buildtools-0.13.5.4
- gtk3-0.15.3
- haskell-gi-0.22.6
- pango-0.13.6.1
- rate-limit-1.4.1
- status-notifier-item-0.3.0.4
- taffybar-3.2.1
- time-units-1.0.0
- xdg-desktop-entry-0.1.1.0
- xml-helpers-1.0.0

resolver: nightly-2019-06-19
