- import_tasks: debian.yml
  when: ansible_os_family == "Debian"


- name: Link nvim config directory
  file:
    src: "{{ dotfiles_home }}/roles/nvim/files/"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
    force: true
