- name: Install zellij with cargo-binstall
  command: "{{ dotfiles_user_home }}/.cargo/bin/cargo-binstall -y zellij"
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/zellij"
  when: not ansible_check_mode

- name: Create zellij config directory
  file:
    path: "{{ xdg_config_home }}/zellij"
    state: directory

- name: Link zellij config.kdl
  file:
    src: "{{ dotfiles_home }}/roles/zellij/files/config.kdl"
    dest: "{{ xdg_config_home }}/zellij/config.kdl"
    state: link
    force: true
